# https://crontab.guru/examples.html

fix_item_urls_job:
  cron: "*/1 * * * *"
  class: "HardWorker"
  queue: hard_worker
scrape_category:
  cron: "0 0 * * *" # every day
  class: "ScrapeCategory"
  queue: hard_worker

scrape_item:
  cron: "0 */2 * * *" # every 2 hours
  class: "ScrapeItem"
  queue: hard_worker

# Perform in scrape_item
process_item:
  cron: "5 */2 * * *" # every 30 minutes
  class: "ProcessItem"
  queue: hard_worker


