name: Build and Push Docker Image

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main
      - master
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push to DockerHub
      with:
        image: 2mui/ui-market-admin
        # tags: ${{ github.sha }}, ${{ steps.docker_meta.outputs.tags }}, latest
        tags: latest, main, ${{ github.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # - uses: mr-smithers-excellent/docker-build-push@v5
    #   name: Build & push to ghcr.io
    #   with:
    #     image: dfang/ui-market-admin
    #     tags: latest, main, ${{ github.sha }}
    #     registry: ghcr.io
    #     username: dfang
    #     password: ${{ secrets.GHCR_TOKEN }}
